### ISSUE TITLE
dbus.exceptions: No such interface `org.gnome.SettingsDaemon.MediaKeys'

### ISSUE THREAD

**Issue by wernight** [borismus/keysocket#54]
When running `keysocket.py`:

```
Traceback (most recent call last):
  File "keysocket.py", line 180, in <module>
    main()
  File "keysocket.py", line 162, in main
    factory = BroadcastServerFactory('ws://localhost:1337')
  File "keysocket.py", line 87, in __init__
    self.keys_listener = DBusMediaKeyListener(callback=self._onMediaKeyEvent)
  File "keysocket.py", line 49, in __init__
    self.app, 0, dbus_interface='org.gnome.SettingsDaemon.MediaKeys')
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface `org.gnome.SettingsDaemon.MediaKeys' on object at path /org/gnome/SettingsDaemon/MediaKeys
```

Using Awesome tiling manager with Gnome on Ubuntu 12.04.02 LTS.

* dbus 1.4.18

**Comment by borismus** [comment]
Obsolete
